// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttach(arg1, arg2) {
  return window['go']['main']['App']['AddAttach'](arg1, arg2);
}

export function AddNoteHistory(arg1, arg2) {
  return window['go']['main']['App']['AddNoteHistory'](arg1, arg2);
}

export function AddNotebook(arg1, arg2) {
  return window['go']['main']['App']['AddNotebook'](arg1, arg2);
}

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function AttachSynced(arg1, arg2) {
  return window['go']['main']['App']['AttachSynced'](arg1, arg2);
}

export function ClearTrash() {
  return window['go']['main']['App']['ClearTrash']();
}

export function ConflictIsFixed(arg1) {
  return window['go']['main']['App']['ConflictIsFixed'](arg1);
}

export function ConflictNote(arg1) {
  return window['go']['main']['App']['ConflictNote'](arg1);
}

export function ContentSynced(arg1, arg2) {
  return window['go']['main']['App']['ContentSynced'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CopyNote(arg1, arg2) {
  return window['go']['main']['App']['CopyNote'](arg1, arg2);
}

export function CopyNotes(arg1, arg2) {
  return window['go']['main']['App']['CopyNotes'](arg1, arg2);
}

export function CopyOtherSiteImage(arg1) {
  return window['go']['main']['App']['CopyOtherSiteImage'](arg1);
}

export function CountAllNotes(arg1) {
  return window['go']['main']['App']['CountAllNotes'](arg1);
}

export function CountNotebooks(arg1) {
  return window['go']['main']['App']['CountNotebooks'](arg1);
}

export function CountNotesByTag(arg1) {
  return window['go']['main']['App']['CountNotesByTag'](arg1);
}

export function CountTags(arg1) {
  return window['go']['main']['App']['CountTags'](arg1);
}

export function CreateLocalAccount(arg1) {
  return window['go']['main']['App']['CreateLocalAccount'](arg1);
}

export function CreateLocalAccountWithPwd(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalAccountWithPwd'](arg1, arg2);
}

export function DeleteAttach(arg1) {
  return window['go']['main']['App']['DeleteAttach'](arg1);
}

export function DeleteImages(arg1) {
  return window['go']['main']['App']['DeleteImages'](arg1);
}

export function DeleteNotExistsAttach(arg1, arg2) {
  return window['go']['main']['App']['DeleteNotExistsAttach'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNoteHistory(arg1) {
  return window['go']['main']['App']['DeleteNoteHistory'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['main']['App']['DeleteNotebook'](arg1);
}

export function DeleteNotes(arg1) {
  return window['go']['main']['App']['DeleteNotes'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DeleteUserAndAllData(arg1) {
  return window['go']['main']['App']['DeleteUserAndAllData'](arg1);
}

export function DownloadImage(arg1) {
  return window['go']['main']['App']['DownloadImage'](arg1);
}

export function DragNotebooks(arg1, arg2, arg3) {
  return window['go']['main']['App']['DragNotebooks'](arg1, arg2, arg3);
}

export function EmitWebEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitWebEvent'](arg1, arg2);
}

export function ExportNote(arg1, arg2) {
  return window['go']['main']['App']['ExportNote'](arg1, arg2);
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function ExportPDFLocal(arg1) {
  return window['go']['main']['App']['ExportPDFLocal'](arg1);
}

export function ExportPDFServer(arg1) {
  return window['go']['main']['App']['ExportPDFServer'](arg1);
}

export function FixContentUrl(arg1) {
  return window['go']['main']['App']['FixContentUrl'](arg1);
}

export function FullSync() {
  return window['go']['main']['App']['FullSync']();
}

export function FullSyncForce() {
  return window['go']['main']['App']['FullSyncForce']();
}

export function GetAllAttachs() {
  return window['go']['main']['App']['GetAllAttachs']();
}

export function GetAllImages() {
  return window['go']['main']['App']['GetAllImages']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetAttach(arg1) {
  return window['go']['main']['App']['GetAttach'](arg1);
}

export function GetAttachDir() {
  return window['go']['main']['App']['GetAttachDir']();
}

export function GetAttachUrl(arg1) {
  return window['go']['main']['App']['GetAttachUrl'](arg1);
}

export function GetAttachsByNote(arg1) {
  return window['go']['main']['App']['GetAttachsByNote'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetCurState() {
  return window['go']['main']['App']['GetCurState']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDataStats() {
  return window['go']['main']['App']['GetDataStats']();
}

export function GetFileBase64(arg1) {
  return window['go']['main']['App']['GetFileBase64'](arg1);
}

export function GetFileJson(arg1) {
  return window['go']['main']['App']['GetFileJson'](arg1);
}

export function GetFileMD5(arg1) {
  return window['go']['main']['App']['GetFileMD5'](arg1);
}

export function GetGlobalConfig() {
  return window['go']['main']['App']['GetGlobalConfig']();
}

export function GetHost() {
  return window['go']['main']['App']['GetHost']();
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetImageDir() {
  return window['go']['main']['App']['GetImageDir']();
}

export function GetImageUrl(arg1) {
  return window['go']['main']['App']['GetImageUrl'](arg1);
}

export function GetLastSyncState() {
  return window['go']['main']['App']['GetLastSyncState']();
}

export function GetLocalNoteId(arg1) {
  return window['go']['main']['App']['GetLocalNoteId'](arg1);
}

export function GetLocalNotebookId(arg1) {
  return window['go']['main']['App']['GetLocalNotebookId'](arg1);
}

export function GetMIMEType(arg1) {
  return window['go']['main']['App']['GetMIMEType'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNoteByServerNoteId(arg1) {
  return window['go']['main']['App']['GetNoteByServerNoteId'](arg1);
}

export function GetNoteContent(arg1) {
  return window['go']['main']['App']['GetNoteContent'](arg1);
}

export function GetNoteHistories(arg1) {
  return window['go']['main']['App']['GetNoteHistories'](arg1);
}

export function GetNotebookByServerId(arg1) {
  return window['go']['main']['App']['GetNotebookByServerId'](arg1);
}

export function GetNotebooks() {
  return window['go']['main']['App']['GetNotebooks']();
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetServerNoteId(arg1) {
  return window['go']['main']['App']['GetServerNoteId'](arg1);
}

export function GetServerNotebookId(arg1) {
  return window['go']['main']['App']['GetServerNotebookId'](arg1);
}

export function GetStarNotes() {
  return window['go']['main']['App']['GetStarNotes']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function GetTrashNotes() {
  return window['go']['main']['App']['GetTrashNotes']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function GetUserAttachsPath(arg1) {
  return window['go']['main']['App']['GetUserAttachsPath'](arg1);
}

export function GetUserByEmail(arg1) {
  return window['go']['main']['App']['GetUserByEmail'](arg1);
}

export function GetUserConfig(arg1) {
  return window['go']['main']['App']['GetUserConfig'](arg1);
}

export function GetUserDBDataStats(arg1) {
  return window['go']['main']['App']['GetUserDBDataStats'](arg1);
}

export function GetUserDBPath(arg1) {
  return window['go']['main']['App']['GetUserDBPath'](arg1);
}

export function GetUserImagesPath(arg1) {
  return window['go']['main']['App']['GetUserImagesPath'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HandleDeepLink(arg1) {
  return window['go']['main']['App']['HandleDeepLink'](arg1);
}

export function HasNotesInNotebook(arg1) {
  return window['go']['main']['App']['HasNotesInNotebook'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IncrSync() {
  return window['go']['main']['App']['IncrSync']();
}

export function IsLocal() {
  return window['go']['main']['App']['IsLocal']();
}

export function IsSyncing() {
  return window['go']['main']['App']['IsSyncing']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function LoginLocal(arg1, arg2) {
  return window['go']['main']['App']['LoginLocal'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function MoveNotes(arg1, arg2) {
  return window['go']['main']['App']['MoveNotes'](arg1, arg2);
}

export function NoteAdded(arg1) {
  return window['go']['main']['App']['NoteAdded'](arg1);
}

export function NoteDeleted(arg1) {
  return window['go']['main']['App']['NoteDeleted'](arg1);
}

export function NoteUpdated(arg1) {
  return window['go']['main']['App']['NoteUpdated'](arg1);
}

export function NotebooksReloaded() {
  return window['go']['main']['App']['NotebooksReloaded']();
}

export function PasteImage(arg1) {
  return window['go']['main']['App']['PasteImage'](arg1);
}

export function ReCountNotebookNumberNotes(arg1) {
  return window['go']['main']['App']['ReCountNotebookNumberNotes'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RebuildImageIndex() {
  return window['go']['main']['App']['RebuildImageIndex']();
}

export function SaveCurState(arg1) {
  return window['go']['main']['App']['SaveCurState'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SearchNotesByTag(arg1) {
  return window['go']['main']['App']['SearchNotesByTag'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetGlobalConfig(arg1) {
  return window['go']['main']['App']['SetGlobalConfig'](arg1);
}

export function SetNoteBlog(arg1, arg2) {
  return window['go']['main']['App']['SetNoteBlog'](arg1, arg2);
}

export function SetNoteError(arg1, arg2) {
  return window['go']['main']['App']['SetNoteError'](arg1, arg2);
}

export function SetNoteIsNew(arg1) {
  return window['go']['main']['App']['SetNoteIsNew'](arg1);
}

export function SetNoteNotDirty(arg1) {
  return window['go']['main']['App']['SetNoteNotDirty'](arg1);
}

export function SetNoteNotDirtyNotDelete(arg1) {
  return window['go']['main']['App']['SetNoteNotDirtyNotDelete'](arg1);
}

export function SetNotebookNotDirty(arg1) {
  return window['go']['main']['App']['SetNotebookNotDirty'](arg1);
}

export function SetNotebookNotDirtyNotDelete(arg1) {
  return window['go']['main']['App']['SetNotebookNotDirtyNotDelete'](arg1);
}

export function SetNotesBlog(arg1, arg2) {
  return window['go']['main']['App']['SetNotesBlog'](arg1, arg2);
}

export function SetSyncProgressCallback() {
  return window['go']['main']['App']['SetSyncProgressCallback']();
}

export function SetTagNotDirty(arg1) {
  return window['go']['main']['App']['SetTagNotDirty'](arg1);
}

export function SetUserConfig(arg1, arg2) {
  return window['go']['main']['App']['SetUserConfig'](arg1, arg2);
}

export function SetUserHost(arg1, arg2) {
  return window['go']['main']['App']['SetUserHost'](arg1, arg2);
}

export function SetWebCallback(arg1) {
  return window['go']['main']['App']['SetWebCallback'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StarNote(arg1) {
  return window['go']['main']['App']['StarNote'](arg1);
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function SwitchUser(arg1) {
  return window['go']['main']['App']['SwitchUser'](arg1);
}

export function SyncError(arg1) {
  return window['go']['main']['App']['SyncError'](arg1);
}

export function SyncFinished(arg1) {
  return window['go']['main']['App']['SyncFinished'](arg1);
}

export function SyncProcess(arg1, arg2) {
  return window['go']['main']['App']['SyncProcess'](arg1, arg2);
}

export function UpdateAllBeLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAllBeLocal'](arg1, arg2, arg3);
}

export function UpdateAttach(arg1, arg2) {
  return window['go']['main']['App']['UpdateAttach'](arg1, arg2);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}

export function UpdateNoteToDeleteTag(arg1) {
  return window['go']['main']['App']['UpdateNoteToDeleteTag'](arg1);
}

export function UpdateNoteUsn(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteUsn'](arg1, arg2);
}

export function UpdateNotebookTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateNotebookTitle'](arg1, arg2);
}

export function UpdateTagCount(arg1) {
  return window['go']['main']['App']['UpdateTagCount'](arg1);
}

export function UpdateUserPwd(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserPwd'](arg1, arg2);
}

export function UploadImage(arg1) {
  return window['go']['main']['App']['UploadImage'](arg1);
}

export function WriteBase64(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBase64'](arg1, arg2, arg3, arg4);
}
