// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddAttach(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AddNoteHistory(arg1:string,arg2:string):Promise<void>;

export function AddNotebook(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AddTag(arg1:string):Promise<void>;

export function AttachSynced(arg1:string,arg2:string):Promise<void>;

export function ClearTrash():Promise<void>;

export function ConflictIsFixed(arg1:string):Promise<void>;

export function ConflictNote(arg1:models.SyncConflict):Promise<void>;

export function ContentSynced(arg1:string,arg2:string):Promise<void>;

export function CopyFile(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function CopyNote(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CopyNotes(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function CopyOtherSiteImage(arg1:string):Promise<Record<string, any>>;

export function CountAllNotes(arg1:string):Promise<number>;

export function CountNotebooks(arg1:string):Promise<number>;

export function CountNotesByTag(arg1:string):Promise<number>;

export function CountTags(arg1:string):Promise<number>;

export function CreateLocalAccount(arg1:string):Promise<Record<string, any>>;

export function CreateLocalAccountWithPwd(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteAttach(arg1:string):Promise<void>;

export function DeleteImages(arg1:string):Promise<void>;

export function DeleteNotExistsAttach(arg1:string,arg2:Array<Record<string, any>>):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteNoteHistory(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<boolean>;

export function DeleteNotes(arg1:Array<string>):Promise<Record<string, any>>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function DeleteUserAndAllData(arg1:string):Promise<Record<string, any>>;

export function DownloadImage(arg1:string):Promise<Record<string, any>>;

export function DragNotebooks(arg1:string,arg2:string,arg3:number):Promise<void>;

export function EmitWebEvent(arg1:string,arg2:any):Promise<void>;

export function ExportNote(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ExportPDF(arg1:string):Promise<Record<string, any>>;

export function ExportPDFLocal(arg1:string):Promise<Record<string, any>>;

export function ExportPDFServer(arg1:string):Promise<Record<string, any>>;

export function FixContentUrl(arg1:string):Promise<string>;

export function FullSync():Promise<Record<string, any>>;

export function FullSyncForce():Promise<Record<string, any>>;

export function GetAllAttachs():Promise<Array<Record<string, any>>>;

export function GetAllImages():Promise<Array<Record<string, any>>>;

export function GetAllUsers():Promise<Array<Record<string, any>>>;

export function GetAttach(arg1:string):Promise<Record<string, any>>;

export function GetAttachDir():Promise<string>;

export function GetAttachUrl(arg1:string):Promise<string>;

export function GetAttachsByNote(arg1:string):Promise<Array<Record<string, any>>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetCurState():Promise<Record<string, string>>;

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetDataStats():Promise<Record<string, number>>;

export function GetFileBase64(arg1:string):Promise<string>;

export function GetFileJson(arg1:string):Promise<Record<string, any>>;

export function GetFileMD5(arg1:string):Promise<string>;

export function GetGlobalConfig():Promise<Record<string, any>>;

export function GetHost():Promise<string>;

export function GetImage(arg1:string):Promise<Record<string, any>>;

export function GetImageDir():Promise<string>;

export function GetImageUrl(arg1:string):Promise<string>;

export function GetLastSyncState():Promise<Record<string, any>>;

export function GetLocalNoteId(arg1:string):Promise<string>;

export function GetLocalNotebookId(arg1:string):Promise<string>;

export function GetMIMEType(arg1:string):Promise<string>;

export function GetNote(arg1:string):Promise<Record<string, any>>;

export function GetNoteByServerNoteId(arg1:string):Promise<Record<string, any>>;

export function GetNoteContent(arg1:string):Promise<Record<string, any>>;

export function GetNoteHistories(arg1:string):Promise<Array<Record<string, any>>>;

export function GetNotebookByServerId(arg1:string):Promise<Record<string, any>>;

export function GetNotebooks():Promise<Array<Record<string, any>>>;

export function GetNotes(arg1:string):Promise<Array<Record<string, any>>>;

export function GetServerNoteId(arg1:string):Promise<string>;

export function GetServerNotebookId(arg1:string):Promise<string>;

export function GetStarNotes():Promise<Array<Record<string, any>>>;

export function GetTags():Promise<Array<Record<string, any>>>;

export function GetToken():Promise<string>;

export function GetTrashNotes():Promise<Array<Record<string, any>>>;

export function GetUser(arg1:string):Promise<Record<string, any>>;

export function GetUserAttachsPath(arg1:string):Promise<string>;

export function GetUserByEmail(arg1:string):Promise<Record<string, any>>;

export function GetUserConfig(arg1:string):Promise<Record<string, any>>;

export function GetUserDBDataStats(arg1:string):Promise<Record<string, any>>;

export function GetUserDBPath(arg1:string):Promise<string>;

export function GetUserImagesPath(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function HandleDeepLink(arg1:string):Promise<Record<string, any>>;

export function HasNotesInNotebook(arg1:string):Promise<boolean>;

export function HideWindow():Promise<void>;

export function IncrSync():Promise<Record<string, any>>;

export function IsLocal():Promise<boolean>;

export function IsSyncing():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function LoginLocal(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;

export function MoveNote(arg1:string,arg2:string):Promise<void>;

export function MoveNotes(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function NoteAdded(arg1:string):Promise<void>;

export function NoteDeleted(arg1:string):Promise<void>;

export function NoteUpdated(arg1:string):Promise<void>;

export function NotebooksReloaded():Promise<void>;

export function PasteImage(arg1:string):Promise<Record<string, any>>;

export function ReCountNotebookNumberNotes(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RebuildImageIndex():Promise<Record<string, any>>;

export function SaveCurState(arg1:Record<string, string>):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<boolean>;

export function SearchNotes(arg1:string):Promise<Array<Record<string, any>>>;

export function SearchNotesByTag(arg1:string):Promise<Array<Record<string, any>>>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetGlobalConfig(arg1:Record<string, string>):Promise<void>;

export function SetNoteBlog(arg1:string,arg2:boolean):Promise<void>;

export function SetNoteError(arg1:string,arg2:string):Promise<void>;

export function SetNoteIsNew(arg1:string):Promise<void>;

export function SetNoteNotDirty(arg1:string):Promise<void>;

export function SetNoteNotDirtyNotDelete(arg1:string):Promise<void>;

export function SetNotebookNotDirty(arg1:string):Promise<void>;

export function SetNotebookNotDirtyNotDelete(arg1:string):Promise<void>;

export function SetNotesBlog(arg1:Array<string>,arg2:boolean):Promise<Record<string, any>>;

export function SetSyncProgressCallback():Promise<void>;

export function SetTagNotDirty(arg1:string):Promise<void>;

export function SetUserConfig(arg1:string,arg2:string):Promise<void>;

export function SetUserHost(arg1:string,arg2:string):Promise<void>;

export function SetWebCallback(arg1:main.WebCallbackFunc):Promise<void>;

export function ShowWindow():Promise<void>;

export function StarNote(arg1:string):Promise<void>;

export function StopSync():Promise<void>;

export function SwitchUser(arg1:string):Promise<void>;

export function SyncError(arg1:models.SyncError):Promise<void>;

export function SyncFinished(arg1:boolean):Promise<void>;

export function SyncProcess(arg1:string,arg2:string):Promise<void>;

export function UpdateAllBeLocal(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function UpdateAttach(arg1:string,arg2:Array<Record<string, any>>):Promise<Record<string, any>>;

export function UpdateNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function UpdateNoteToDeleteTag(arg1:string):Promise<void>;

export function UpdateNoteUsn(arg1:string,arg2:number):Promise<void>;

export function UpdateNotebookTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateTagCount(arg1:string):Promise<void>;

export function UpdateUserPwd(arg1:string,arg2:string):Promise<void>;

export function UploadImage(arg1:string):Promise<Record<string, any>>;

export function WriteBase64(arg1:string,arg2:boolean,arg3:string,arg4:string):Promise<Record<string, any>>;
